// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Whisprr.Contracts.Enums;
using Whisprr.SocialListeningScheduler.Data;

#nullable disable

namespace Whisprr.SocialListeningScheduler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224144953_UpdateTaskProgressStatusAddQueued")]
    partial class UpdateTaskProgressStatusAddQueued
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_progress_status", new[] { "pending", "processing", "queued", "success", "failed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Whisprr.SocialListeningScheduler.Models.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("Whisprr.SocialListeningScheduler.Models.SocialListeningTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SocialTopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourcePlatformId")
                        .HasColumnType("uuid");

                    b.Property<TaskProgressStatus>("Status")
                        .HasColumnType("task_progress_status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SocialTopicId");

                    b.HasIndex("SourcePlatformId");

                    b.ToTable("SocialListeningTasks");
                });

            modelBuilder.Entity("Whisprr.SocialListeningScheduler.Models.SocialTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialTopics");
                });

            modelBuilder.Entity("Whisprr.SocialListeningScheduler.Models.SocialListeningTask", b =>
                {
                    b.HasOne("Whisprr.SocialListeningScheduler.Models.SocialTopic", "SocialTopic")
                        .WithMany("SocialListeningTasks")
                        .HasForeignKey("SocialTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whisprr.SocialListeningScheduler.Models.DataSource", "DataSource")
                        .WithMany("SocialListeningTasks")
                        .HasForeignKey("SourcePlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataSource");

                    b.Navigation("SocialTopic");
                });

            modelBuilder.Entity("Whisprr.SocialListeningScheduler.Models.DataSource", b =>
                {
                    b.Navigation("SocialListeningTasks");
                });

            modelBuilder.Entity("Whisprr.SocialListeningScheduler.Models.SocialTopic", b =>
                {
                    b.Navigation("SocialListeningTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
