/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UnauthOnlyRouteImport } from './routes/_unauth-only'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthOnlyRegisterRouteImport } from './routes/_unauth-only.register'
import { Route as UnauthOnlyLoginRouteImport } from './routes/_unauth-only.login'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthOnlyRoute = UnauthOnlyRouteImport.update({
  id: '/_unauth-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthOnlyRegisterRoute = UnauthOnlyRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UnauthOnlyRoute,
} as any)
const UnauthOnlyLoginRoute = UnauthOnlyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthOnlyRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof UnauthOnlyLoginRoute
  '/register': typeof UnauthOnlyRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof AuthDashboardRoute
  '/login': typeof UnauthOnlyLoginRoute
  '/register': typeof UnauthOnlyRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_unauth-only': typeof UnauthOnlyRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_unauth-only/login': typeof UnauthOnlyLoginRoute
  '/_unauth-only/register': typeof UnauthOnlyRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/dashboard' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dashboard' | '/login' | '/register'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_unauth-only'
    | '/about'
    | '/_auth/dashboard'
    | '/_unauth-only/login'
    | '/_unauth-only/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UnauthOnlyRoute: typeof UnauthOnlyRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth-only': {
      id: '/_unauth-only'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth-only/register': {
      id: '/_unauth-only/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthOnlyRegisterRouteImport
      parentRoute: typeof UnauthOnlyRoute
    }
    '/_unauth-only/login': {
      id: '/_unauth-only/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthOnlyLoginRouteImport
      parentRoute: typeof UnauthOnlyRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UnauthOnlyRouteChildren {
  UnauthOnlyLoginRoute: typeof UnauthOnlyLoginRoute
  UnauthOnlyRegisterRoute: typeof UnauthOnlyRegisterRoute
}

const UnauthOnlyRouteChildren: UnauthOnlyRouteChildren = {
  UnauthOnlyLoginRoute: UnauthOnlyLoginRoute,
  UnauthOnlyRegisterRoute: UnauthOnlyRegisterRoute,
}

const UnauthOnlyRouteWithChildren = UnauthOnlyRoute._addFileChildren(
  UnauthOnlyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UnauthOnlyRoute: UnauthOnlyRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
